name: 'test'

on:
  workflow_dispatch

jobs:
  facadapi:
    name: 'Unit test'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    - name: git repo Checkout
      uses: actions/checkout@v2      

    - name: Setup Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'adopt'		
        cache: maven

    - name: unit test
      run:  mvn clean test
